import { Inter } from 'next/font/google';
import { Providers } from './providers';
import Navbar from './components/Navbar';
import './globals.css'
import { FirebaseProvider } from './context/firebase';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <>

      <html lang="en" />
      <head>
        <style>{`.${inter.className} { font-family: ${inter.fontFamily}; }`}</style>
      </head>
      <body>
        <FirebaseProvider>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </FirebaseProvider>
      </body>
    </>

  )
}
